[build]
  base = "react-todo-app"
  command = "npm run build"
  publish = "react-todo-app/build"

[build.environment]
  NODE_VERSION = "20"
  NODE_OPTIONS = "--openssl-legacy-provider"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
